# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30a511adfd66bc04efed1bd5f49c25624dbf4d8599a0078588b0c09c001b8ca0caff6e100d1753676d0d6b9637711a874348be6c936e41c19e2718e6aa1d832c

test:
  secret_key_base: 5f003516452a7211c233b5e005119a6d77bd33704dffa527e246d18f827f9a2fe4203befd44bf89c6b8b0bd8bfc31c486fb8d00d610fca79074a921b3accbbce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
